### ISSUE TITLE
better landing page

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/wdc-saas-starter-kit#3]

**Comment by iamabhigupta** [comment]
Hi Sir, I would love to work on a better landing page for it. Can i start working on it?

**Comment by iamabhigupta** [comment]
I have some questions 
1. Can i change the content on the page like h2 paragraphs? 
2. Can we use any color theme like purple blue green? any ?

**Comment by webdevcody** [comment]
you're welcome to change whatever as long as you don't copy code from another component library unless it's already MIT.  In regards to themes, I think they are already pretty configurable in the global.css defined as css color variables.  I think whatever theme you use should be based on that file (or you can add more colors to that file) so that the entire starter kit can be easily re-themed.

**Comment by harrykamboj1** [comment]
@webdevcody I've made some changes in the Landing Page, and here's the new look.

![Screenshot 2024-07-17 001654](https://github.com/user-attachments/assets/7b4c1488-bedc-427c-8b80-e47b06e7d661)


https://github.com/user-attachments/assets/0280a70a-1290-40ca-a981-dc58f2b1a941
