### ISSUE TITLE
Build Error with @aws-sdk/s3-request-presigner

### ISSUE THREAD

**Issue by evert-arias** [webdevcody/wdc-saas-starter-kit#8]
While building for production I encountered the following error with @aws-sdk/s3-request-presigner:

```bash
./node_modules/@aws-sdk/s3-request-presigner/dist-es/index.js + 34 modules
Cannot get final name for export 'booleanSelector' of ./node_modules/@smithy/util-config-provider/dist-es/index.js
```

**Comment by evert-arias** [comment]
As a workaround, I added the package to the serverComponentsExternalPackages array in the experimental object of next.config.mjs:

```javascript
experimental: {
  serverComponentsExternalPackages: ["@aws-sdk/s3-request-presigner"],
},
```

**Comment by webdevcody** [comment]
thanks, I'll add that in an see if I can get this deployed.  I won't lie, I haven't even tried deploying this code yet.  Going to do that now

**Comment by evert-arias** [comment]
@webdevcody, I found a few additional issues when attempting to deploy this to production. I'd be happy to submit a PR with the fixes that worked for me.

**Comment by evert-arias** [comment]
@webdevcody By the way, this template is great. It has my preferred stack and is well-structured. Thanks for putting this all together!

**Comment by webdevcody** [comment]
@evert-arias thanks man, tried my best to make it feel as polished as time would allow.  reach out if you have any suggestions.  I did your suggestion to the next.config which fixed the issue.  I may close this for now since we have a quick "hack" solution.
